
# server.port=8181
server:
  port: 8181

# 로그 설정
logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /myapi.html

# database connection
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/demodb
    username: root
    password: mariadb